export const START_HOUSE_FETCH = 'START_HOUSE_FETCH'
export const FETCH_HOUSE_SUCCESS = 'FETCH_HOUSE_SUCCESS'

export const START_SENATE_FETCH = 'START_SENATE_FETCH'
export const FETCH_SENATE_SUCCESS = 'FETCH_SENATE_SUCCESS'

export const START_STATE_FETCH = 'START_STATE_FETCH'
export const FETCH_STATE_SUCCESS = 'FETCH_STATE_SUCCESS'

export const START_SHOW_STATE_FETCH = 'START_SHOW_STATE_FETCH'
export const FETCH_SHOW_STATE_SUCCESS = 'FETCH_SHOW_STATE_SUCCESS'

export const START_SHOW_HOUSE_REP_FETCH = 'START_SHOW_HOUSE_REP_FETCH'
export const FETCH_SHOW_HOUSE_REP_SUCCESS = 'FETCH_SHOW_HOUSE_REP_SUCCESS'

export const START_SHOW_SENATOR_FETCH = 'START_SHOW_SENATOR_FETCH'
export const FETCH_SHOW_SENATOR_SUCCESS = 'FETCH_SHOW_SENATOR_SUCCESS'