export const START_HOUSE_FETCH = 'START_HOUSE_FETCH'
export const FETCH_HOUSE_SUCCESS = 'FETCH_HOUSE_SUCCESS'

export const START_SENATE_FETCH = 'START_SENATE_FETCH'
export const FETCH_SENATE_SUCCESS = 'FETCH_SENATE_SUCCESS'

export const START_STATE_FETCH = 'START_STATE_FETCH'
export const FETCH_STATE_SUCCESS = 'FETCH_STATE_SUCCESS'

export const START_SHOW_STATE_FETCH = 'START_SHOW_STATE_FETCH'
export const FETCH_SHOW_STATE_SUCCESS = 'FETCH_SHOW_STATE_SUCCESS'

export const START_SHOW_HOUSE_REP_FETCH = 'START_SHOW_HOUSE_REP_FETCH'
export const FETCH_SHOW_HOUSE_REP_SUCCESS = 'FETCH_SHOW_HOUSE_REP_SUCCESS'

export const START_SHOW_SENATOR_FETCH = 'START_SHOW_SENATOR_FETCH'
export const FETCH_SHOW_SENATOR_SUCCESS = 'FETCH_SHOW_SENATOR_SUCCESS'

export const START_LOGIN_USER_FETCH = 'START_LOGIN_USER_FETCH'
export const FETCH_LOGIN_USER_SUCCESS = 'FETCH_LOGIN_USER_SUCCESS'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const START_VERIFY_USER_FETCH = 'START_VERIFY_USER_FETCH'
export const FETCH_VERIFY_USER_SUCCESS = 'FETCH_VERIFY_USER_SUCCESS'

export const START_UPDATE_USER_FETCH = 'START_UPDATE_USER_FETCH'
export const FETCH_UPDATE_USER_SUCCESS = 'FETCH_UPDATE_USER_SUCCESS'

export const START_REGISTER_USER_FETCH = 'START_REGISTER_USER_FETCH'
export const FETCH_REGISTER_USER_SUCCESS = 'FETCH_REGISTER_USER_SUCCESS'

export const START_DELETE_USER_FETCH = 'START_DELETE_USER_FETCH'
export const FETCH_DELETE_USER_SUCCESS = 'FETCH_DELETE_USER_SUCCESS'

export const START_COMPARE_REP_FETCH = 'START_COMPARE_REP_FETCH'
export const FETCH_COMPARE_REP_SUCCESS = 'FETCH_COMPARE_REP_SUCCESS'
export const START_COMPARE_SENATOR_FETCH = 'START_COMPARE_SENATOR_FETCH'
export const FETCH_COMPARE_SENATOR_SUCCESS = 'FETCH_COMPARE_SENATOR_SUCCESS'

export const START_REMOVE_COMPARE_SENATOR = 'START_REMOVE_COMPARE_SENATOR'
export const REMOVE_COMPARE_SENATOR_SUCCESS = 'REMOVE_COMPARE_SENATOR_SUCCESS'

export const START_REMOVE_COMPARE_REP = 'START_REMOVE_COMPARE_REP'
export const REMOVE_COMPARE_REP_SUCCESS = 'REMOVE_COMPARE_REP_SUCCESS'